<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-03 19:33
=======
# Generated by Django 3.0.7 on 2020-10-02 15:52
>>>>>>> 9685caf2b3a34308bc58ce04c2baa3a1b023f3c3

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
